/**
 * Asset Model
 *
 * Defines the schema for fashion/clothing assets used in the AI matching system.
 * Stores clothing items with their categories, images, and AI embeddings for similarity matching.
 */

import mongoose from "mongoose";

const AssetSchema = new mongoose.Schema({
  // Name/description of the clothing item
  name: String,

  // Category classification (limited to shirt, pant, shoe)
  category: { type: String, enum: ["shirt", "pant", "shoe"] },

  // Path/URL to the asset image
  imagePath: String,

  // AI embedding vector for similarity matching (generated by CLIP or similar model)
  embedding: [Number],
});

export default mongoose.model("Asset", AssetSchema);